export const types = {
  CREATE_ROOM: 'CREATE_ROOM',
  ROOM_CREATED: 'ROOM_CREATED',
  JOIN_ROOM: 'JOIN_ROOM',
  ROOM_JOINED: 'ROOM_JOINED',
  UPDATE_FIELD: 'UPDATE_FIELD',
  UPDATE_STATE: 'UPDATE_STATE',
  UPDATE_PLAYERS: 'UPDATE_PLAYERS',
  START_SESSION: 'START_SESSION',
  SESSION_STARTED: 'SESSION_STARTED',
  PLAY_CARD: 'PLAY_CARD',
}
