module.exports = {
  CREATE_ROOM: 'CREATE_ROOM',
  ROOM_CREATED: 'ROOM_CREATED',
  JOIN_ROOM: 'JOIN_ROOM',
  ROOM_JOINED: 'ROOM_JOINED',
  REMOVE_ROOM: 'REMOVE_ROOM',
  UPDATE_STATE: 'UPDATE_STATE',
}
