module.exports = {
  CREATE_ROOM: 'CREATE_ROOM',
  ROOM_CREATED: 'ROOM_CREATED',
  JOIN_ROOM: 'JOIN_ROOM',
  ROOM_JOINED: 'ROOM_JOINED',
  REMOVE_ROOM: 'REMOVE_ROOM',
  UPDATE_PLAYERS: 'UPDATE_PLAYERS',
  UPDATE_CHOICES: 'UPDATE_CHOICES',
  UPDATE_STATE: 'UPDATE_STATE',
  START_SESSION: 'START_SESSION',
  SESSION_STARTED: 'SESSION_STARTED',
  PLAY_CARD: 'PLAY_CARD',
}
